plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.28-beta'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

neoForge {
	version = project.neoforge_version
	
	parchment {
		minecraftVersion = project.minecraft_version
		mappingsVersion = "2024.07.28"
	}

	runs {
		client {
			client()
		}
		server {
			server()
		}
	}

	mods {
		worldexport {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
	maven {
		name = "CurseForge"
		url = "https://www.cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}
	maven { url 'https://jitpack.io' }
}

dependencies {
	implementation "net.neoforged:neoforge:${neoforge_version}"

	// ReforgedPlay (Neoforge version of ReplayMod)
	compileOnly "curse.maven:reforgedplay-1018692:${project.reforgedplay_file_id}"
	runtimeOnly "curse.maven:reforgedplay-1018692:${project.reforgedplay_file_id}"
	
	implementation("com.github.LlamaLad7:MixinExtras:0.4.1")
	annotationProcessor("com.github.LlamaLad7:MixinExtras:0.4.1")
	
	implementation('de.javagl:obj:0.3.0')
	implementation('org.joml:joml:1.10.2')

	testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
}

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
		minecraft_version: minecraft_version,
		minecraft_version_range: minecraft_version_range,
		neoforge_version: neoforge_version,
		neoforge_version_range: neoforge_version_range,
		loader_version_range: loader_version_range,
		mod_id: mod_id,
		mod_name: mod_name,
		mod_license: mod_license,
		mod_version: mod_version,
		mod_authors: mod_authors,
		mod_description: mod_description,
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties + [project: project]
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

test {
	useJUnitPlatform()
}

// Thanks to Modmuss for helping with this task!
tasks.register('addon', Zip) {
	from "addon"
	archiveBaseName = "import_vcap"
	destinationDirectory = project.layout.buildDirectory.dir("libs")
	
	filesMatching("**/__init__.py") {
		filter {
			it.replace("(0, 0, 0)", "(${version.replaceAll("[^\\d.]", "").split("\\.").join(", ")})")
			
		}
	}

	exclude "**/__pycache__*"
	exclude "*.py[cod]"
	exclude "*.py.class"
}