# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
# Fuerza a Gradle a usar JDK 21 incluso si `java` del sistema es 11
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64

# Neoforge Properties
	minecraft_version=1.21.1
	minecraft_version_range=[1.21.1,1.22)
	neoforge_version=21.1.192
	neoforge_version_range=[21.1,21.2)
	loader_version_range=[4,)
# Mod Properties
	mod_version = 0.9.3
	maven_group = org.scaffoldeditor
	archives_base_name = mc-world-export
	mod_id = worldexport
	mod_name = Igrium's Replay Exporter
	mod_license = GPL-3.0-or-later
	mod_authors = Igrium
	mod_description = An addon to the Replay Mod that allows it to export into Blender and other 3D software.

# Dependencies
	reforgedplay_version=1.21.1-1.0.3
	reforgedplay_file_id=6942967
